import type {
    CartItem,
    Category,
    DeliveryItem,
    Order,
    Product,
    SalesStats,
} from '@/types/store';

// Mock Categories
export const mockCategories: Category[] = [
    {
        id: 1,
        name: 'T-Shirts',
        slug: 't-shirts',
        image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=400&fit=crop',
        productCount: 24,
    },
    {
        id: 2,
        name: 'Pants',
        slug: 'pants',
        image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=400&h=400&fit=crop',
        productCount: 18,
    },
    {
        id: 3,
        name: 'Jackets',
        slug: 'jackets',
        image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400&h=400&fit=crop',
        productCount: 12,
    },
    {
        id: 4,
        name: 'Dresses',
        slug: 'dresses',
        image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=400&fit=crop',
        productCount: 15,
    },
    {
        id: 5,
        name: 'Hoodies',
        slug: 'hoodies',
        image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=400&h=400&fit=crop',
        productCount: 10,
    },
    {
        id: 6,
        name: 'Accessories',
        slug: 'accessories',
        image: 'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=400&h=400&fit=crop',
        productCount: 30,
    },
];

// Mock Products
export const mockProducts: Product[] = [
    {
        id: 1,
        name: 'Classic White Tee',
        slug: 'classic-white-tee',
        description:
            'A timeless white t-shirt made from 100% organic cotton. Comfortable fit with a clean, minimalist design perfect for everyday wear. Features reinforced stitching and a pre-shrunk fabric that maintains its shape wash after wash.',
        price: 29.99,
        compareAtPrice: 39.99,
        category: 'T-Shirts',
        images: [
            {
                id: 1,
                url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&h=800&fit=crop',
                alt: 'Classic White Tee front',
            },
            {
                id: 2,
                url: 'https://images.unsplash.com/photo-1622445275576-721325763afe?w=600&h=800&fit=crop',
                alt: 'Classic White Tee back',
            },
        ],
        variants: [
            {
                id: 1,
                size: 'XS',
                color: 'White',
                colorHex: '#FFFFFF',
                stock: 15,
                sku: 'CWT-XS-W',
            },
            {
                id: 2,
                size: 'S',
                color: 'White',
                colorHex: '#FFFFFF',
                stock: 20,
                sku: 'CWT-S-W',
            },
            {
                id: 3,
                size: 'M',
                color: 'White',
                colorHex: '#FFFFFF',
                stock: 25,
                sku: 'CWT-M-W',
            },
            {
                id: 4,
                size: 'L',
                color: 'White',
                colorHex: '#FFFFFF',
                stock: 18,
                sku: 'CWT-L-W',
            },
            {
                id: 5,
                size: 'XL',
                color: 'White',
                colorHex: '#FFFFFF',
                stock: 10,
                sku: 'CWT-XL-W',
            },
            {
                id: 6,
                size: 'S',
                color: 'Black',
                colorHex: '#000000',
                stock: 22,
                sku: 'CWT-S-B',
            },
            {
                id: 7,
                size: 'M',
                color: 'Black',
                colorHex: '#000000',
                stock: 30,
                sku: 'CWT-M-B',
            },
            {
                id: 8,
                size: 'L',
                color: 'Black',
                colorHex: '#000000',
                stock: 15,
                sku: 'CWT-L-B',
            },
        ],
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        colors: [
            { name: 'White', hex: '#FFFFFF' },
            { name: 'Black', hex: '#000000' },
        ],
        featured: true,
        createdAt: '2025-12-01',
    },
    {
        id: 2,
        name: 'Slim Fit Black Jeans',
        slug: 'slim-fit-black-jeans',
        description:
            'Modern slim-fit black jeans crafted from premium stretch denim. Features a comfortable mid-rise waist, tapered leg, and classic 5-pocket styling. The perfect foundation for any outfit.',
        price: 79.99,
        category: 'Pants',
        images: [
            {
                id: 3,
                url: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&h=800&fit=crop',
                alt: 'Slim Fit Black Jeans',
            },
        ],
        variants: [
            {
                id: 9,
                size: 'S',
                color: 'Black',
                colorHex: '#000000',
                stock: 12,
                sku: 'SBJ-S-B',
            },
            {
                id: 10,
                size: 'M',
                color: 'Black',
                colorHex: '#000000',
                stock: 18,
                sku: 'SBJ-M-B',
            },
            {
                id: 11,
                size: 'L',
                color: 'Black',
                colorHex: '#000000',
                stock: 14,
                sku: 'SBJ-L-B',
            },
            {
                id: 12,
                size: 'XL',
                color: 'Black',
                colorHex: '#000000',
                stock: 8,
                sku: 'SBJ-XL-B',
            },
        ],
        sizes: ['S', 'M', 'L', 'XL'],
        colors: [{ name: 'Black', hex: '#000000' }],
        featured: true,
        createdAt: '2025-11-15',
    },
    {
        id: 3,
        name: 'Leather Bomber Jacket',
        slug: 'leather-bomber-jacket',
        description:
            'Premium faux leather bomber jacket with quilted lining. Features ribbed cuffs and hem, two front pockets, and a smooth YKK zipper closure. A statement piece that elevates any casual look.',
        price: 149.99,
        compareAtPrice: 199.99,
        category: 'Jackets',
        images: [
            {
                id: 4,
                url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&h=800&fit=crop',
                alt: 'Leather Bomber Jacket',
            },
        ],
        variants: [
            {
                id: 13,
                size: 'S',
                color: 'Black',
                colorHex: '#000000',
                stock: 5,
                sku: 'LBJ-S-B',
            },
            {
                id: 14,
                size: 'M',
                color: 'Black',
                colorHex: '#000000',
                stock: 8,
                sku: 'LBJ-M-B',
            },
            {
                id: 15,
                size: 'L',
                color: 'Black',
                colorHex: '#000000',
                stock: 6,
                sku: 'LBJ-L-B',
            },
            {
                id: 16,
                size: 'S',
                color: 'Brown',
                colorHex: '#8B4513',
                stock: 4,
                sku: 'LBJ-S-BR',
            },
            {
                id: 17,
                size: 'M',
                color: 'Brown',
                colorHex: '#8B4513',
                stock: 7,
                sku: 'LBJ-M-BR',
            },
            {
                id: 18,
                size: 'L',
                color: 'Brown',
                colorHex: '#8B4513',
                stock: 3,
                sku: 'LBJ-L-BR',
            },
        ],
        sizes: ['S', 'M', 'L'],
        colors: [
            { name: 'Black', hex: '#000000' },
            { name: 'Brown', hex: '#8B4513' },
        ],
        featured: true,
        createdAt: '2025-10-20',
    },
    {
        id: 4,
        name: 'Floral Summer Dress',
        slug: 'floral-summer-dress',
        description:
            'Light and breezy floral print midi dress perfect for summer days. Features a V-neckline, adjustable tie-waist, and flowy A-line silhouette. Made from breathable viscose fabric.',
        price: 59.99,
        category: 'Dresses',
        images: [
            {
                id: 5,
                url: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&h=800&fit=crop',
                alt: 'Floral Summer Dress',
            },
        ],
        variants: [
            {
                id: 19,
                size: 'XS',
                color: 'Floral',
                colorHex: '#FFB6C1',
                stock: 10,
                sku: 'FSD-XS-F',
            },
            {
                id: 20,
                size: 'S',
                color: 'Floral',
                colorHex: '#FFB6C1',
                stock: 14,
                sku: 'FSD-S-F',
            },
            {
                id: 21,
                size: 'M',
                color: 'Floral',
                colorHex: '#FFB6C1',
                stock: 12,
                sku: 'FSD-M-F',
            },
            {
                id: 22,
                size: 'L',
                color: 'Floral',
                colorHex: '#FFB6C1',
                stock: 8,
                sku: 'FSD-L-F',
            },
        ],
        sizes: ['XS', 'S', 'M', 'L'],
        colors: [{ name: 'Floral', hex: '#FFB6C1' }],
        featured: true,
        createdAt: '2025-09-10',
    },
    {
        id: 5,
        name: 'Oversized Hoodie',
        slug: 'oversized-hoodie',
        description:
            'Ultra-comfortable oversized hoodie made from heavyweight French terry cotton. Features a kangaroo pocket, adjustable drawstring hood, and ribbed cuffs. Perfect for layering or lounging.',
        price: 69.99,
        category: 'Hoodies',
        images: [
            {
                id: 6,
                url: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600&h=800&fit=crop',
                alt: 'Oversized Hoodie',
            },
        ],
        variants: [
            {
                id: 23,
                size: 'S',
                color: 'Gray',
                colorHex: '#808080',
                stock: 20,
                sku: 'OH-S-G',
            },
            {
                id: 24,
                size: 'M',
                color: 'Gray',
                colorHex: '#808080',
                stock: 25,
                sku: 'OH-M-G',
            },
            {
                id: 25,
                size: 'L',
                color: 'Gray',
                colorHex: '#808080',
                stock: 18,
                sku: 'OH-L-G',
            },
            {
                id: 26,
                size: 'XL',
                color: 'Gray',
                colorHex: '#808080',
                stock: 12,
                sku: 'OH-XL-G',
            },
            {
                id: 27,
                size: 'S',
                color: 'Black',
                colorHex: '#000000',
                stock: 15,
                sku: 'OH-S-B',
            },
            {
                id: 28,
                size: 'M',
                color: 'Black',
                colorHex: '#000000',
                stock: 20,
                sku: 'OH-M-B',
            },
            {
                id: 29,
                size: 'L',
                color: 'Black',
                colorHex: '#000000',
                stock: 16,
                sku: 'OH-L-B',
            },
        ],
        sizes: ['S', 'M', 'L', 'XL'],
        colors: [
            { name: 'Gray', hex: '#808080' },
            { name: 'Black', hex: '#000000' },
        ],
        featured: false,
        createdAt: '2025-08-05',
    },
    {
        id: 6,
        name: 'Striped Polo Shirt',
        slug: 'striped-polo-shirt',
        description:
            'Classic striped polo shirt with a modern fit. Made from premium piqué cotton with a soft hand feel. Features a ribbed collar, two-button placket, and side vents for comfort.',
        price: 44.99,
        category: 'T-Shirts',
        images: [
            {
                id: 7,
                url: 'https://images.unsplash.com/photo-1625910513413-5fc421e0e5f0?w=600&h=800&fit=crop',
                alt: 'Striped Polo Shirt',
            },
        ],
        variants: [
            {
                id: 30,
                size: 'S',
                color: 'Navy',
                colorHex: '#000080',
                stock: 10,
                sku: 'SPS-S-N',
            },
            {
                id: 31,
                size: 'M',
                color: 'Navy',
                colorHex: '#000080',
                stock: 15,
                sku: 'SPS-M-N',
            },
            {
                id: 32,
                size: 'L',
                color: 'Navy',
                colorHex: '#000080',
                stock: 12,
                sku: 'SPS-L-N',
            },
            {
                id: 33,
                size: 'XL',
                color: 'Navy',
                colorHex: '#000080',
                stock: 8,
                sku: 'SPS-XL-N',
            },
        ],
        sizes: ['S', 'M', 'L', 'XL'],
        colors: [{ name: 'Navy', hex: '#000080' }],
        featured: false,
        createdAt: '2025-07-22',
    },
    {
        id: 7,
        name: 'Cargo Jogger Pants',
        slug: 'cargo-jogger-pants',
        description:
            'Versatile cargo jogger pants with an elastic waistband and tapered leg. Features multiple utility pockets, drawstring ankle cuffs, and a relaxed comfortable fit.',
        price: 54.99,
        category: 'Pants',
        images: [
            {
                id: 8,
                url: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600&h=800&fit=crop',
                alt: 'Cargo Jogger Pants',
            },
        ],
        variants: [
            {
                id: 34,
                size: 'S',
                color: 'Olive',
                colorHex: '#808000',
                stock: 14,
                sku: 'CJP-S-O',
            },
            {
                id: 35,
                size: 'M',
                color: 'Olive',
                colorHex: '#808000',
                stock: 20,
                sku: 'CJP-M-O',
            },
            {
                id: 36,
                size: 'L',
                color: 'Olive',
                colorHex: '#808000',
                stock: 16,
                sku: 'CJP-L-O',
            },
            {
                id: 37,
                size: 'S',
                color: 'Black',
                colorHex: '#000000',
                stock: 12,
                sku: 'CJP-S-B',
            },
            {
                id: 38,
                size: 'M',
                color: 'Black',
                colorHex: '#000000',
                stock: 18,
                sku: 'CJP-M-B',
            },
            {
                id: 39,
                size: 'L',
                color: 'Black',
                colorHex: '#000000',
                stock: 14,
                sku: 'CJP-L-B',
            },
        ],
        sizes: ['S', 'M', 'L'],
        colors: [
            { name: 'Olive', hex: '#808000' },
            { name: 'Black', hex: '#000000' },
        ],
        featured: false,
        createdAt: '2025-06-18',
    },
    {
        id: 8,
        name: 'Denim Trucker Jacket',
        slug: 'denim-trucker-jacket',
        description:
            'Classic denim trucker jacket with a modern twist. Made from premium washed denim with a slight stretch. Features chest pockets, adjustable waist tabs, and antique brass buttons.',
        price: 89.99,
        category: 'Jackets',
        images: [
            {
                id: 9,
                url: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=600&h=800&fit=crop',
                alt: 'Denim Trucker Jacket',
            },
        ],
        variants: [
            {
                id: 40,
                size: 'S',
                color: 'Blue',
                colorHex: '#4169E1',
                stock: 7,
                sku: 'DTJ-S-BL',
            },
            {
                id: 41,
                size: 'M',
                color: 'Blue',
                colorHex: '#4169E1',
                stock: 10,
                sku: 'DTJ-M-BL',
            },
            {
                id: 42,
                size: 'L',
                color: 'Blue',
                colorHex: '#4169E1',
                stock: 8,
                sku: 'DTJ-L-BL',
            },
            {
                id: 43,
                size: 'XL',
                color: 'Blue',
                colorHex: '#4169E1',
                stock: 5,
                sku: 'DTJ-XL-BL',
            },
        ],
        sizes: ['S', 'M', 'L', 'XL'],
        colors: [{ name: 'Blue', hex: '#4169E1' }],
        featured: false,
        createdAt: '2025-05-30',
    },
];

// Mock Cart Items
export const mockCartItems: CartItem[] = [
    {
        id: 1,
        product: mockProducts[0],
        variant: mockProducts[0].variants[2], // M, White
        quantity: 2,
    },
    {
        id: 2,
        product: mockProducts[2],
        variant: mockProducts[2].variants[1], // M, Black
        quantity: 1,
    },
    {
        id: 3,
        product: mockProducts[4],
        variant: mockProducts[4].variants[1], // M, Gray
        quantity: 1,
    },
];

// Mock Orders
export const mockOrders: Order[] = [
    {
        id: 1,
        orderNumber: 'JCS-2026-001',
        items: [
            {
                id: 1,
                productName: 'Classic White Tee',
                productImage:
                    'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=100&h=100&fit=crop',
                size: 'M',
                color: 'White',
                quantity: 2,
                price: 29.99,
            },
            {
                id: 2,
                productName: 'Leather Bomber Jacket',
                productImage:
                    'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=100&h=100&fit=crop',
                size: 'M',
                color: 'Black',
                quantity: 1,
                price: 149.99,
            },
        ],
        total: 209.97,
        status: 'completed',
        shippingAddress: '123 Main St, Manila, Philippines',
        customerName: 'Juan Dela Cruz',
        customerEmail: 'juan@example.com',
        createdAt: '2026-01-15',
        updatedAt: '2026-01-20',
    },
    {
        id: 2,
        orderNumber: 'JCS-2026-002',
        items: [
            {
                id: 3,
                productName: 'Slim Fit Black Jeans',
                productImage:
                    'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=100&h=100&fit=crop',
                size: 'L',
                color: 'Black',
                quantity: 1,
                price: 79.99,
            },
        ],
        total: 79.99,
        status: 'processing',
        shippingAddress: '456 Oak Ave, Cebu City, Philippines',
        customerName: 'Maria Santos',
        customerEmail: 'maria@example.com',
        createdAt: '2026-02-10',
        updatedAt: '2026-02-12',
    },
    {
        id: 3,
        orderNumber: 'JCS-2026-003',
        items: [
            {
                id: 4,
                productName: 'Floral Summer Dress',
                productImage:
                    'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=100&h=100&fit=crop',
                size: 'S',
                color: 'Floral',
                quantity: 1,
                price: 59.99,
            },
            {
                id: 5,
                productName: 'Oversized Hoodie',
                productImage:
                    'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=100&h=100&fit=crop',
                size: 'M',
                color: 'Gray',
                quantity: 2,
                price: 69.99,
            },
        ],
        total: 199.97,
        status: 'pending',
        shippingAddress: '789 Pine Rd, Davao City, Philippines',
        customerName: 'Pedro Reyes',
        customerEmail: 'pedro@example.com',
        createdAt: '2026-02-25',
        updatedAt: '2026-02-25',
    },
    {
        id: 4,
        orderNumber: 'JCS-2026-004',
        items: [
            {
                id: 6,
                productName: 'Striped Polo Shirt',
                productImage:
                    'https://images.unsplash.com/photo-1625910513413-5fc421e0e5f0?w=100&h=100&fit=crop',
                size: 'L',
                color: 'Navy',
                quantity: 3,
                price: 44.99,
            },
        ],
        total: 134.97,
        status: 'shipped',
        shippingAddress: '321 Elm St, Quezon City, Philippines',
        customerName: 'Ana Garcia',
        customerEmail: 'ana@example.com',
        createdAt: '2026-02-20',
        updatedAt: '2026-02-23',
    },
];

// Mock Sales Stats
export const mockSalesStats: SalesStats = {
    totalRevenue: 24589.5,
    totalOrders: 156,
    totalProducts: 48,
    totalCustomers: 89,
    revenueChange: 12.5,
    ordersChange: 8.3,
};

// Mock Delivery Items
export const mockDeliveries: DeliveryItem[] = [
    {
        id: 1,
        orderNumber: 'JCS-2026-002',
        customerName: 'Maria Santos',
        address: '456 Oak Ave, Cebu City',
        status: 'in-transit',
        estimatedDate: '2026-03-01',
        trackingNumber: 'TRK-001234',
    },
    {
        id: 2,
        orderNumber: 'JCS-2026-003',
        customerName: 'Pedro Reyes',
        address: '789 Pine Rd, Davao City',
        status: 'preparing',
        estimatedDate: '2026-03-05',
        trackingNumber: 'TRK-001235',
    },
    {
        id: 3,
        orderNumber: 'JCS-2026-004',
        customerName: 'Ana Garcia',
        address: '321 Elm St, Quezon City',
        status: 'in-transit',
        estimatedDate: '2026-02-28',
        trackingNumber: 'TRK-001236',
    },
    {
        id: 4,
        orderNumber: 'JCS-2026-001',
        customerName: 'Juan Dela Cruz',
        address: '123 Main St, Manila',
        status: 'delivered',
        estimatedDate: '2026-01-20',
        trackingNumber: 'TRK-001230',
    },
];

// Helper to format price
export function formatPrice(price: number): string {
    return `₱${price.toFixed(2)}`;
}
